name: Build Web

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/web/**'
      - '.github/workflows/build-web.yaml'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/robinwongm/wechat-dnt/web
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: packages/web
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
